"""Data contracts shared with the agent.

Pydantic models for ``request.json`` (what the agent asks for), ``summary.json`` (what the
pipeline produces) and chart specifications. These schemas are versioned with
``schema_version``; any breaking change bumps it and updates ``references/request-schema.md``.
"""

from wiki_interest.contracts.charts import ChartKind, ChartSeries, ChartSize, ChartSpec
from wiki_interest.contracts.request import (
    EARLIEST_MONTH,
    AnalysisRequest,
    BundleMode,
    Period,
    QuestionType,
    RankingWeightsSpec,
    ReportOptions,
    SubstituteChoice,
    SubstituteSpec,
    TopicSpec,
)
from wiki_interest.contracts.summary import (
    AnalysisSummary,
    ArticleOut,
    Artifacts,
    AssessmentOut,
    BundleOut,
    CandidateOut,
    CheckOut,
    Clarification,
    ComparisonRow,
    ContextArticleOut,
    CoverageGapOut,
    CoverageOptionOut,
    DecisionOut,
    EvidenceOut,
    FindingOut,
    MetricsOut,
    PointOut,
    Provenance,
    RankedRow,
    ReliabilityOut,
    SeriesOut,
    TopicResolutionOut,
    Verdict,
)

__all__ = [
    "EARLIEST_MONTH",
    "AnalysisRequest",
    "AnalysisSummary",
    "ArticleOut",
    "Artifacts",
    "AssessmentOut",
    "BundleMode",
    "BundleOut",
    "CandidateOut",
    "ChartKind",
    "ChartSeries",
    "ChartSize",
    "ChartSpec",
    "CheckOut",
    "Clarification",
    "ComparisonRow",
    "ContextArticleOut",
    "CoverageGapOut",
    "CoverageOptionOut",
    "DecisionOut",
    "EvidenceOut",
    "FindingOut",
    "MetricsOut",
    "Period",
    "PointOut",
    "Provenance",
    "QuestionType",
    "RankedRow",
    "RankingWeightsSpec",
    "ReliabilityOut",
    "ReportOptions",
    "SeriesOut",
    "SubstituteChoice",
    "SubstituteSpec",
    "TopicResolutionOut",
    "TopicSpec",
    "Verdict",
]
